services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    image: llc:v1
    container_name: llc-app
    ports:
      - "8080:8080"
    depends_on:
      db:
        condition: service_healthy
    env_file:
      - .env

  db:
    image: mysql:8.0
    container_name: mysql-db
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: password
      MYSQL_DATABASE: llc
    ports:
      - "3307:3306"
    volumes:
      - db_data:/var/lib/mysql
      - ./llc.sql:/docker-entrypoint-initdb.d/database.sql
    healthcheck:
      test: ["CMD-SHELL", "mysqladmin ping -uroot -ppassword"]
      interval: 5s
      timeout: 5s
      retries: 10

volumes:
  db_data:
